easy_admin:
  site_name: '<strong> Haničko here you can customize your website:) </strong>'

  user:
    name_property_path: 'email'
    display_name: true
    display_avatar: false

  design:
    form_theme:
        - '@EasyAdmin/form/bootstrap_4.html.twig'
        - '@VichUploader/Form/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    assets:
      css:
        - '/css/easyadmin.css'
    menu:
      - { label: Back to your website, icon: arrow-left, route: accueil}

      - { entity: 'Articles', label: 'Articles', icon: 'book'}
      - { entity: 'Contact', label: 'Contact', icon: 'id-card'}
      - { entity: 'Comments', label: 'Comments', icon: 'comments'}
      - { entity: 'Content', label: 'Content Home Page', icon: 'book'}
      - { entity: 'GalleryAdmin', label: 'Gallery Admin', icon: 'image'}
     

  entities:
      Articles:
        class: App\Entity\Articles  
        list:
          fields: 
            - { property: 'featured_image', title: 'title', label: 'Image', type: 'image', base_path: '%app.path.featured_images%'}
            - { property: 'active', label: Published, type: 'toggle'}
            - { property: 'date_creation', label: Crée}
            - { property: 'title', label: Title}
            - { property: 'text', label: Contenu }
            - { property: 'author', label: Author}
            
        form:
          fields:
            - title
            - author
            - { property: 'text', type: 'fos_ckeditor', type_options: {config_name: 'main_config' }}
            - { property: 'imageFile', template: 'article.html.twig', type: 'vich_image', label: 'Image'} 
        
        templates:
          edit: 'easyadmin/articles/edit.html.twig'
      
      
      # -------
      Contact:
        class: App\Entity\Contact
        disabled_actions: [new, edit]
        templates:
          list: 'easyadmin/contact/list.html.twig'
 
      
      Comments:
        class: App\Entity\Comments
        disabled_actions: [new, edit]
        templates:
          list: 'easyadmin/comments/list.html.twig'

      Content:
        class: App\Entity\Content
        disabled_actions: [new, delete]
        list:
          fields: 
            - { property: 'name', label: Quel texte ?}
            # - { property: 'image', label: Image, type: image}
            - { property: 'content_image', label: 'Image' , type: 'image', base_path: '%app.path.content_images%'}
            - { property: 'text', label: Text}
        form:
          fields:
            # - { property: image, label: URL de l'image }
            - { property: 'imageFile', template: 'index.html.twig', type: 'vich_image', label: 'Upload image', help: 'Select file to upload / change image' }
            - { property: 'text', type: 'fos_ckeditor', type_options: {config_name: 'main_config'}}
        
        templates:
          edit: 'easyadmin/content/edit.html.twig'
          
      GalleryAdmin:
        class: App\Entity\GalleryAdmin
        list:
          fields: 
            - { property: 'gallery_image', label: 'Image' , type: 'image', base_path: '%app.path.gallery_images%'}

        form:
          fields:
            - { property: 'imageFile', type: 'vich_image', label: 'Upload image', help: 'Select file to upload / change image' }
        templates:
          list: 'easyadmin/galleryAdmin/list.html.twig'
        