# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    # default_config: main_config
    configs:
        main_config:
            toolbar: full
                
            # toolbar:
            #    - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike','Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source'] }
            #    - { name: "editor2" , items: ['imageuploader']}
            #filebrowserBrowseRoute: elfinder
            #filebrowserBrowseRouteParameters: []

            filebrowserImageUploadRoute: admin_upload_image
            filebrowserImageUploadRouteParameters: { upload: 1 }
            filebrowserImageUploadRouteType: 0

            filebrowserImageBrowseRoute: admin_browse_image
            filebrowserImageBrowseRouteParameters: { upload: 1 }
            filebrowserImageBrowseRouteType: 0