# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: gd

    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - '%public_path%'

    filter_sets: # Contient la liste des filtres
        carre: # Nom du filtre
            quality: 100 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [95, 63] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
        reduc:
            quality: 100
            filters:
                thumbnail: { size: [570, 380], mode: outbound }
        
        my_crop_filter:
            filters:

                # use and setup the "crop" filter
                crop:

                    # set the size of the cropping area
                    size: [ 300, 250 ]

                    # # set the starting coordinates of the crop
                    # start: [ 040, 160 ]
          
        article:
            quality: 100
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: 'public/images/logoYom1.jpg'
                    # size of the water mark relative to the input image
                    size: 0.1
                    # set the position of the watermark
                    position: bottomright